version: "3"
networks:
    john-test-wordpress-6.1.1-net:
        driver: bridge

services:
    mysql:
        image: mysql:8
        container_name: john-test-wordpress-6.1.1-mysql
        tty: true
        ports:
            - "3306:3306"
        volumes:
            - "./var/libclea/mysql/:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: wordpress
            MYSQL_USER: john
            MYSQL_PASSWORD: secret
        networks:
            - john-test-wordpress-6.1.1-net

    server:
        image: wordpress:latest
        container_name: john-test-wordpress-6.1.1
        ports:
            - "80:80"
        volumes:
            - "./var/www/html/:/var/www/html"
        environment:
            WORDPRESS_DB_USER: john
            WORDPRESS_DB_PASSWORD: secret
            WORDPRESS_DB_NAME: wordpress
            WORDPRESS_DB_HOST: john-test-wordpress-6.1.1-mysql
        depends_on:
            - mysql
        networks:
            - john-test-wordpress-6.1.1-net

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: ds-phpmyadmin
        ports:
            - "8000:80"
        environment:
            PMA_HOST: john-test-wordpress-6.1.1-mysql
            MYSQL_ROOT_PASSWORD: secret
        depends_on:
            - mysql
        networks:
            - john-test-wordpress-6.1.1-net